import "../styles/globals.css";
import store from "../store/store";
import { Provider } from "react-redux";
import type { AppProps } from "next/app";
import Layout from "../components/Default UI/Layout";
import Head from "next/head";

function MyApp({ Component, pageProps: { ...pageProps } }: AppProps) {
    return (
        <Provider store={store}>
            <Head>
                <title>Mamiru</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <Component {...pageProps} />
            </Layout>
        </Provider>
    );
}

export default MyApp;
